### ISSUE TITLE
HISTDUP=erase has no purpose in zsh

### ISSUE THREAD

**Issue by davidculley** [elliottminns/dotfiles#2]
I suppose you can remove that line.

https://github.com/elliottminns/dotfiles/blob/17d0f76ad1a8f10e871622c0babf048557228d29/.zshrc#L55

[As far as I know](https://zsh.sourceforge.io/Doc/Release/Parameters.html#Parameters-Used-By-The-Shell), there is no parameter named `HISTDUP` in `zsh`. That parameter seems to be specific to `tcsh`.

Or did I miss something?

**Comment by elliottminns** [comment]
I think you're correct

**Comment by elliottminns** [comment]
Removed!
